export const OPERATOR = {
  AND: 'AND',
  OR: 'OR',
  '<': 'lt',
  '<=': 'lte',
  '>': 'gt',
  '>=': 'gte',
  '=': 'equals',
  '!=': 'notEquals',
  IN: 'in',
  NOT: 'not',
  'NOT IN': 'notIn',
  SW: 'startsWith',
  'STARTS WITH': 'startsWith',
  EW: 'endsWith',
  'ENDS WITH': 'startsWith',
  CONTAINS: 'contains',
} as const;
